package com.interviewprep.output;

import com.fasterxml.jackson.annotation.JsonPropertyDescription;

/**
 * Structured output record representing an AI-generated evaluation of a user's answer.
 * <p>
 * This record is used as the deserialized target for Spring AI's native structured output when evaluating
 * coding or theory answers via the {@link com.interviewprep.question.AiGatewayService}. The AI model returns
 * a JSON object matching this schema, which is then mapped to an {@link com.interviewprep.domain.Evaluation} entity.
 * </p>
 * <h3>Fields:</h3>
 * <ul>
 *   <li>{@code score} — numeric rating from 0-10 indicating answer quality.</li>
 *   <li>{@code strengths} — list of positive aspects identified in the user's answer.</li>
 *   <li>{@code weaknesses} — list of areas for improvement.</li>
 *   <li>{@code improvedAnswer} — a better version of the answer or solution code.</li>
 *   <li>{@code isCorrect} — whether the coding solution is algorithmically correct (null for theory).</li>
 *   <li>{@code correctnessExplanation} — explanation for the correctness assessment.</li>
 *   <li>{@code timeComplexity} — Big-O time complexity in notation (null for theory).</li>
 *   <li>{@code spaceComplexity} — Big-O space complexity in notation (null for theory).</li>
 * </ul>
 * 
 * @see com.interviewprep.domain.Evaluation
 * @see com.interviewprep.question.AiGatewayService
 */
public record EvaluationRecord(
    /** Score rating of 0-10 for answer quality. */
    @JsonPropertyDescription("Score rating of 0-10 for answer quality") int score,
    /** What the user did well — positive aspects identified by the AI evaluator. */
    @JsonPropertyDescription("What the user did well") java.util.List<String> strengths,
    /** Areas for improvement identified in the user's answer. */
    @JsonPropertyDescription("Areas for improvement") java.util.List<String> weaknesses,
    /** Better version of the answer or improved solution code generated by the AI. */
    @JsonPropertyDescription("Better version of the answer or improved solution code") String improvedAnswer,
    /** Whether the coding solution is algorithmically correct (null for theory evaluation). */
    @JsonPropertyDescription("Whether the coding solution is algorithmically correct (null for theory evaluation)") Boolean isCorrect,
    /** Explanation of correctness assessment (null for theory evaluation). */
    @JsonPropertyDescription("Explanation of correctness assessment (null for theory evaluation)") String correctnessExplanation,
    /** Algorithmic time complexity in Big-O notation (null for theory evaluation). */
    @JsonPropertyDescription("Algorithmic time complexity in Big-O notation (null for theory evaluation)") String timeComplexity,
    /** Algorithmic space complexity in Big-O notation (null for theory evaluation). */
    @JsonPropertyDescription("Algorithmic space complexity in Big-O notation (null for theory evaluation)") String spaceComplexity
) {
}
