package com.interviewprep.domain;

import jakarta.persistence.*;

/**
 * JPA entity representing a category in the interview preparation platform's hierarchical topic structure.
 * <p>
 * Categories form a tree-like hierarchy where each category can have a parent category, enabling
 * organization of interview topics into broad subject areas (e.g., "Data Structures" → "Arrays", "Trees").
 * Each category has a unique name and a type that distinguishes between different kinds of content.
 * </p>
 * <p>
 * Table: {@code categories}
 * </p>
 */
@Entity
@Table(name = "categories")
public class Category {

    /** Unique database identifier for this category, auto-generated by the database. */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /** Display name of the category (e.g., "Data Structures", "Arrays"). Must be unique across all categories. */
    @Column(nullable = false, unique = true)
    private String name;

    /** Type classification for this category, used to differentiate between topic types and organize content. */
    @Column(nullable = false)
    private String type;

    /** Parent category in the hierarchy. Null for root-level categories. Lazy-loaded to avoid unnecessary joins. */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "parent_id", foreignKey = @ForeignKey(name = "fk_categories_parent"))
    private Category parent;

    /** Default no-arg constructor required by JPA for entity instantiation. */
    public Category() {}

    /** Returns the unique identifier for this category. */
    public Long getId() { return id; }
    public void setId(Long id) { this.id = id; }

    /** Returns the display name of this category. */
    public String getName() { return name; }
    public void setName(String name) { this.name = name; }

    /** Returns the type classification for this category. */
    public String getType() { return type; }
    public void setType(String type) { this.type = type; }

    /** Returns the parent category, or null if this is a root-level category. */
    public Category getParent() { return parent; }
    public void setParent(Category parent) { this.parent = parent; }
}
